[package]

description = "A trivially modified version of the bindgen created cql bindings plus a working example with no additional dependencies.\nYou probably want to use the \"cassandra\" crate that provides a safe wrapper"
license = "Apache-2.0"
name = "cql_bindgen"
version = "0.0.15"
authors = ["Tupshin Harper <tupshin@tupshin.com>"]
build = "build.rs"

[lib]
name = "cql_bindgen"

[[bin]]
name="basic"
path="src/examples/basic.rs"

[[bin]]
name="schema_meta"
path="src/examples/schema_meta.rs"

[[bin]]
name="uuid"
path="src/examples/uuid.rs"

[[bin]]
name="async"
path="src/examples/async.rs"

[dependencies]
libc = "*"
